export const spacesData = [
  {
    id: 1,
    title: "Website Development",
    desc: "High-performance websites crafted for growth.",
    tagline: "Build with Purpose",
    category: "Web",
    image: "/spaces/space (1).webp",
    clientName: "",
    clientImage: "/spaces/space (1).webp",
    route: "",
  },
  {
    id: 2,
    title: "eCommerce Solutions",
    desc: "Scalable online stores engineered for conversions.",
    tagline: "Sell Smarter",
    category: "Commerce",
    image: "/spaces/space (17).webp",
    clientName: "",
    clientImage: "/spaces/space (1).webp",
    route: "",
  },
  {
    id: 3,
    title: "Mobile App Development",
    desc: "Intuitive iOS & Android apps built for scale.",
    tagline: "Apps That Scale",
    category: "Apps",
    image: "/spaces/space (20).webp",
    clientName: "",
    clientImage: "/spaces/space (20).webp",
    route: "",
  },
  {
    id: 4,
    title: "UI/UX Design",
    desc: "User-centered design that boosts engagement.",
    tagline: "Feel the Flow",
    category: "Design",
    image: "/spaces/space (8).webp",
    clientName: "",
    clientImage: "/spaces/space (8).webp",
    route: "",
  },
  {
    id: 5,
    title: "SEO Optimization",
    desc: "Search strategies that drive long-term visibility.",
    tagline: "Rank & Rise",
    category: "SEO",
    image: "/spaces/space (7).webp",
    clientName: "",
    clientImage: "/spaces/space (7).webp",
    route: "",
  },
  {
    id: 6,
    title: "Google Ads Management",
    desc: "ROI-focused campaigns that convert better.",
    tagline: "Spend Smart",
    category: "Ads",
    image: "/spaces/space (2).webp",
    clientName: "",
    clientImage: "/spaces/space (2).webp",
    route: "",
  },
  {
    id: 7,
    title: "Social Media Marketing",
    desc: "Creative strategies that grow communities.",
    tagline: "Influence More",
    category: "Social",
    image: "/spaces/space (22).webp",
    clientName: "",
    clientImage: "/spaces/space (22).webp",
    route: "",
  },
  {
    id: 8,
    title: "Content Marketing",
    desc: "Strategic content crafted for conversions.",
    tagline: "Words That Win",
    category: "Content",
    image: "/spaces/space (15).webp",
    clientName: "",
    clientImage: "/spaces/space (1).webp",
    route: "",
  },
  {
    id: 9,
    title: "DevOps & Automation",
    desc: "Automated pipelines for faster deployments.",
    tagline: "Deploy Faster",
    category: "DevOps",
    image: "/spaces/space (21).webp",
    clientName: "",
    clientImage: "/spaces/space (1).webp",
    route: "",
  },
  {
    id: 10,
    title: "Cloud Solutions",
    desc: "Secure and scalable cloud infrastructures.",
    tagline: "Scale Effortlessly",
    category: "Cloud",
    image: "/spaces/space (12).webp",
    clientName: "",
    clientImage: "/spaces/space (1).webp",
    route: "",
  },
  {
    id: 11,
    title: "API Development",
    desc: "Robust APIs crafted for seamless integrations.",
    tagline: "Connect Everything",
    category: "Backend",
    image: "/spaces/space (6).webp",
    clientName: "",
    clientImage: "/spaces/space (6).webp",
    route: "",
  },
  {
    id: 12,
    title: "Automotive Websites",
    desc: "High-impact digital experiences for auto brands.",
    tagline: "Drive Digital",
    category: "Auto",
    image: "/spaces/space (10).webp",
    clientName: "",
    clientImage: "/spaces/space (10).webp",
    route: "",
  },
  {
    id: 13,
    title: "Dashboard Development",
    desc: "Custom dashboards that simplify decisions.",
    tagline: "Data, Delivered",
    category: "Dashboards",
    image: "/spaces/space (11).webp",
    clientName: "",
    clientImage: "/spaces/space (11).webp",
    route: "",
  },
  {
    id: 14,
    title: "Marketplace Platforms",
    desc: "Multi-vendor platforms built to scale fast.",
    tagline: "Scale Multi-Vendor",
    category: "Marketplace",
    image: "/spaces/space (18).webp",
    clientName: "",
    clientImage: "/spaces/space (18).webp",
    route: "",
  },
  {
    id: 15,
    title: "Branding & Identity",
    desc: "Timeless branding systems for modern businesses.",
    tagline: "Make It Iconic",
    category: "Branding",
    image: "/spaces/space (5).webp",
    clientName: "",
    clientImage: "/spaces/space (1).webp",
    route: "",
  },
];
